### ISSUE TITLE
Translatable?

### ISSUE THREAD

**Issue by Regnander** [Darkhax-Minecraft/OldJavaWarning#3]
Can you make this mod translatable?

**Comment by Darkhax** [comment]
Yes, I can make this mod translatable. I don't know how useful that will be since the mod happens before players can change their language option though.

**Comment by Regnander** [comment]
What if players already have set their language before installing the mod while playing vanilla MC (like myself)?
Otherwise they would get the translated message once a new Java update is released.

**Comment by Darkhax** [comment]
That's a fair use case. I was thinking this mod was mainly used by modpacks.

**Comment by Darkhax** [comment]
Okay, I have made this mod translatable. The GUI bodies use HTML so you can actually change the layout a fair bit. Please try to stick to the same format though.

**Comment by Regnander** [comment]
Okay, thanks! I'll bear that in mind when I translate it.
